name: M3U Purge & Sync
on:
  schedule:
    - cron: '45 */12 * * *' # Roda a cada 12 horas
  workflow_dispatch:      # Para você rodar manualmente quando quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set permissions
        run: chmod +x scripts/clean-m3u.sh

      - name: Run Clean Script
        run: ./scripts/clean-m3u.sh

      - name: Commit e Push se houver mudanças
        run: |
            git config user.name "M3U-Cleaner-Bot"
            git config user.email "bot@github.com"
          
            # Adiciona o arquivo gerado
            git add external/My_list.m3u8
            
            # O segredo: verificamos o status sem deixar o shell falhar
            if [ -n "$(git status --porcelain external/My_list.m3u8)" ]; then
              echo "Mudanças detectadas. Commitando..."
              git commit -m "Update: Lista M3U limpa em $(date +'%d/%m/%Y %H:%M')"
              git push
            else
              echo "Nenhuma mudança relevante no conteúdo da lista. Pulando commit."
            fi
  